[build]
  # Directory that contains the deploy-ready HTML files and assets
  publish = "_site/"
  # Default build command.
  command = "bundle exec jekyll build"

# cache fonts forever
[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=365000000, immutable"