[build]
  # Directory that contains the deploy-ready HTML files and assets
  publish = "_public/"
  # Default build command.
  command = "npm run publish"

[context.production]
  environment = { NODE_VERSION = "15" }

# cache fonts forever
[[headers]]
  for = "/assets/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=365000000, immutable"

# fail the build if there are any broken links
[[plugins]]
  package = "netlify-plugin-checklinks"
    [plugins.inputs]
    entryPoints = [
      "*.html",
    ]
    recursive = true
    pretty = true
    skipPatterns = [".js", "#"]
    todoPatterns = []
    checkExternal = false
    followSourceMaps = false